SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE NOT IN ('Spayed Female', 'Neutered Male')
AND B.SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
ORDER BY A.ANIMAL_ID ASC;