SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P JOIN APPOINTMENT AS A ON P.PT_NO = A.PT_NO
JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE A.APNT_CNCL_YN = 'N' AND DATE(A.APNT_YMD) = '2022-04-13' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;