WITH RECURSIVE a AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h + 1 FROM a WHERE h < 23
)

SELECT a.h AS HOUR, COUNT(o.ANIMAL_ID) AS COUNT
FROM a LEFT JOIN ANIMAL_OUTS AS o
ON a.h = HOUR(o.DATETIME)
GROUP BY a.h
ORDER BY a.h;